{
  "os": [
    "linux"
  ],
  "sudo": true,
  "deploy": [
    {
      "on": {
        "branch": [
          "src"
        ]
      },
      "script": "bash deploy.sh",
      "provider": "script",
      "skip_cleanup": true
    },
    {
      "on": {
        "branch": [
          "src"
        ]
      },
      "token": "${GITHUB_TOKEN}",
      "provider": "pages",
      "local_dir": "./public/",
      "keep_history": true,
      "skip_cleanup": true,
      "target_branch": "master"
    }
  ],
  "script": [
    "hexo clean",
    "hexo g",
    "mv ./other/* ./public",
    "rm -rf other/",
    "hexo d"
  ],
  "install": [
    "sudo apt-get install enca -y",
    "npm install -g hexo-cli",
    "npm install -g hexo"
  ],
  "node_js": [
    "10"
  ],
  "branches": {
    "only": [
      "src"
    ]
  },
  "language": "node_js",
  "after_install": [
    "hexo -v"
  ],
  "before_install": [
    "openssl aes-256-cbc -K $encrypted_6b5b110e1eb2_key -iv $encrypted_6b5b110e1eb2_iv -in __config.yml.enc -out _config.yml -d"
  ]
}
