language: node_js
node_js:
- '10'
branches:
  only:
  - src
before_install:
- openssl aes-256-cbc -K $encrypted_6b5b110e1eb2_key -iv $encrypted_6b5b110e1eb2_iv -in __config.yml.enc -out _config.yml -d
- openssl aes-256-cbc -K $encrypted_6b5b110e1eb2_key -iv $encrypted_6b5b110e1eb2_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
- npm -v
- node -v
install:
- npm install -g hexo-cli
- npm install -g hexo
after_install:
- hexo -v
before_deploy:
- hexo clean
- hexo g
- mv ./other/* ./public
- rm -rf other/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "${GITHUB_TOKEN}"
  keep_history: true
  local_dir: "./public/"
  target_branch: master
  on:
    branch: src
after_deploy:
- git config --global user.name "Mryan05"
- git config --global user.email "a2564011261@163.com"
- cd ./public
- rm -rf .git
- git init
- git add .
- git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"  # 提交记录包含时间 跟上面更改时区配合
- git push --force --quiet "https://${Travis_Token}@git.dev.tencent.com/Mryan05/mryan05.coding.me.git" master:master
after_success:
- hexo d