language: node_js
node_js:
- '10'
branches:
  only:
    - src
install:
- npm install -g hexo-cli
- npm install -g hexo
before_deploy:
- hexo clean
- hexo g
- mv ./other/ ./public/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: ./public/
  target_branch: master
  on:
    branch: src