let SearchService=(()=>{const o={};o.queryText=null;o.data=null;o.template=`<div id="u-search">
  <div class="modal">
    <header class="modal-header" class="clearfix">
      <form id="u-search-modal-form" class="u-search-form" name="uSearchModalForm">
        <input type="text" id="u-search-modal-input" class="u-search-input" />
        <button type="submit" id="u-search-modal-btn-submit" class="u-search-btn-submit">
          <span class="fa-solid fa-search"></span>
        </button>
      </form>
      <a id="u-search-btn-close" class="btn-close"> <span class="fa-solid fa-times"></span> </a>
    </header>
    <main class="modal-body">
      <ul class="modal-results"></ul>
    </main>
  </div>
  <div id="modal-overlay" class="modal-overlay"></div>
</div>
`;o.init=()=>{let e=document.createElement("div");e.innerHTML+=o.template;document.body.append(e);document.querySelectorAll(".u-search-form").forEach(e=>{e.addEventListener("submit",o.onSubmit,false)});let t=document.querySelector("#u-search-modal-input");t.addEventListener("input",o.onSubmit);document.querySelector("#u-search-btn-close").addEventListener("click",o.close,false);document.querySelector("#modal-overlay").addEventListener("click",o.close,false)};o.onSubmit=e=>{e.preventDefault();let t=e.target.querySelector(".u-search-input");if(t){o.queryText=t.value}else{o.queryText=e.target.value}if(o.queryText){o.search()}};o.search=async()=>{document.querySelectorAll(".u-search-input").forEach(e=>{e.value=o.queryText});document.querySelector("#u-search").style.display="block";if(!o.data){o.data=await o.fetchData()}let e="";e+=o.buildResultList(o.data.pages);e+=o.buildResultList(o.data.posts);document.querySelector("#u-search .modal-results").innerHTML=e;window.pjax&&pjax.refresh(document.querySelector("#u-search"));document.addEventListener("keydown",function e(t){if(t.code==="Escape"){o.close();document.removeEventListener("keydown",e)}})};o.close=()=>{document.querySelector("#u-search").style.display="none"};o.fetchData=()=>{return fetch(SearchServiceDataPath).then(e=>e.text()).then(e=>{const t=JSON.parse(e);return t})};o.buildResultList=e=>{let t="";e.forEach(e=>{if(e.text){e.text=e.text.replace(/12345\d*/g,"")}if(!e.title&&e.text){e.title=e.text.trim().slice(0,15)}if(o.contentSearch(e)){t+=o.buildResult(e.permalink,e.title,e.digest)}});return t};o.contentSearch=l=>{let a=l.title.trim().toLowerCase();let r=l.text.trim().toLowerCase();let s=o.queryText.trim().toLowerCase().split(/[-\s]+/);let i=false;let n=-1;let c=-1;let u=-1;if(a&&r){s.forEach((e,t)=>{n=a.indexOf(e);c=r.indexOf(e);if(n<0&&c<0){i=false}else{i=true;if(c<0){c=0}if(t===0){u=c}}if(i){r=l.text.trim();let e=0;let t=0;if(u>=0){e=Math.max(u-40,0);t=e===0?Math.min(200,r.length):Math.min(u+120,r.length);let a=r.substring(e,t);s.forEach(function(e){let t=new RegExp(e,"gi");a=a.replace(t,"<b mark>"+e+"</b>")});l.digest=a+"......"}else{t=Math.min(200,r.length);l.digest=r.trim().substring(0,t)}}})}return i};o.buildResult=(e,t,a)=>{let l=o.getUrlRelativePath(e);let r="";r+="<li>";r+="<a class='result' href='"+l+"?keyword="+o.queryText+"'>";r+="<span class='title'>"+t+"</span>";if(a!=="")r+="<span class='digest'>"+a+"</span>";r+="</a>";r+="</li>";return r};o.getUrlRelativePath=function(e){let t=e.split("//");let a=t[1].indexOf("/");let l=t[1].substring(a);if(l.indexOf("?")!=-1){l=l.split("?")[0]}return l};return{init:()=>{o.init()},setQueryText:e=>{o.queryText=e},search:()=>{o.search()}}})();Object.freeze(SearchService);SearchService.init();document.addEventListener("pjax:success",SearchService.init);document.addEventListener("pjax:send",function(){document.querySelector("#u-search").style.display="none"});