# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Hexo CI

on:
  push:
    branches: [ "src" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Hexo
      run: |
        npm install -g hexo-cli
        npm install
    - name: clean
      run: hexo clean
    - name: generate
      run: hexo generate
    - name: hexo generate again
      run: hexo generate
    - name: Copy
      run: |
        mkdir ../public
        cp -r ./public/* ../public
    - name: Deploy
      run: |
        git config --global user.name 'Mryan2005'
        git config --global user.email 'A2564011261@163.com'
        git fetch
        git checkout origin/master
        git pull
        rm -rf *
        cp -r ../public/* ./
        git add .
        git commit -m "Update"
        git push
    - name: Clean
      run: |
        rm -rf ../public
    - name: Finish
      run: |
        echo "Finish"
