name: Push to Baidu and Bing
on: 
    workflow_run: 
        workflows: ["Hexo CI"]
        types:
            - completed
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: switch to gh-pages
          run: |
            git fetch origin gh-pages:gh-pages
            git checkout gh-pages
        - uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: install dependencies
          run: |
            pip install requests
        - name: push to baidu and Bing
          run: python3 ./pushToBaidu.py ${{secrets.SITEURL}} ${{secrets.BAIDUTOKEN}} ${{secrets.BINGTOKEN}}
        - name: Using IndexNew push
          run: |
            echo ${{secrets.BINGINDEXNEWTOKEN}} > ${{secrets.BINGINDEXNEWTOKEN}}.txt
            python3 ./pushToBingIndexNew.py IndexNew ${{secrets.BINGINDEXNEWTOKEN}}
