name: Push to Baidu
on: 
    workflow_run: 
        workflows: ["Hexo CI"]
        types:
            - completed
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: switch to gh-pages
          run: |
            git fetch origin gh-pages:gh-pages
            git checkout gh-pages
        - uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        - name: run py file
          run: |
            pip install requests  
        - name: push to baidu
          run: python3 ./pushToBaidu.py ${{secrets.SITEURL}}
        - name: commit
          run: curl -H 'Content-Type:text/plain' --data-binary @url.txt "http://data.zz.baidu.com/urls?site=${{secrets.SITEURL}}&token=${{secrets.BAIDUTOKEN}}"